### ISSUE TITLE
dont run locally

### ISSUE THREAD

**Issue by johnfelipe** [Autodesk-Forge/forge-react-boiler.nodejs#4]
git clone https://github.com/Autodesk-Forge/forge-react-boiler.nodejs.git

	cd forge-react-boiler.nodejs/

	npm install

	set NODE_ENV=development

	set HOT_RELOADING=true

	sudo nano /home/felipe/forge-react-boiler.nodejs/config/development.config.js

	##
	const PORT = process.env.PORT || 3010
	##

	npm start

and this is error log:

	> forge-react-boiler@2.0.0 start /home/felipe/forge-react-boiler.nodejs
	> node bin/start.js

	uncaughtException
	{ Error: listen EADDRINUSE :::3000
		at Object.exports._errnoException (util.js:1020:11)
		at exports._exceptionWithHostPort (util.js:1043:20)
		at Server._listen2 (net.js:1262:14)
		at listen (net.js:1298:10)
		at Server.listen (net.js:1394:5)
		at EventEmitter.listen (/home/felipe/forge-react-boiler.nodejs/node_modules/express/lib/application.js:618:24)
		at runServer (/home/felipe/forge-react-boiler.nodejs/bin/server/index.js:269:22)
		at Object.<anonymous> (/home/felipe/forge-react-boiler.nodejs/bin/server/index.js:293:1)
		at Module._compile (module.js:570:32)
		at Object.Module._extensions..js (module.js:579:10)
	  code: 'EADDRINUSE',
	  errno: 'EADDRINUSE',
	  syscall: 'listen',
	  address: '::',
	  port: 3000 }
	Error: listen EADDRINUSE :::3000
		at Object.exports._errnoException (util.js:1020:11)
		at exports._exceptionWithHostPort (util.js:1043:20)
		at Server._listen2 (net.js:1262:14)
		at listen (net.js:1298:10)
		at Server.listen (net.js:1394:5)
		at EventEmitter.listen (/home/felipe/forge-react-boiler.nodejs/node_modules/express/lib/application.js:618:24)
		at runServer (/home/felipe/forge-react-boiler.nodejs/bin/server/index.js:269:22)
		at Object.<anonymous> (/home/felipe/forge-react-boiler.nodejs/bin/server/index.js:293:1)
		at Module._compile (module.js:570:32)
		at Object.Module._extensions..js (module.js:579:10)
	dist/ directory not found, starting compiler ...
	Starting compiler NODE_ENV=undefined
	Unhandled Rejection at: Promise  Promise {
	  <rejected> { Error: Cannot find module './undefined.webpack.config'
		at Function.Module._resolveFilename (module.js:469:15)
		at Function.Module._load (module.js:417:25)
		at Module.require (module.js:497:17)
		at require (internal/module.js:20:19)
		at build (/home/felipe/forge-react-boiler.nodejs/webpack/index.js:42:25)
		at clean.then (/home/felipe/forge-react-boiler.nodejs/webpack/index.js:61:3) code: 'MODULE_NOT_FOUND' } }  reason:  { Error: Cannot find module './undefined.webpack.config'
		at Function.Module._resolveFilename (module.js:469:15)
		at Function.Module._load (module.js:417:25)
		at Module.require (module.js:497:17)
		at require (internal/module.js:20:19)
		at build (/home/felipe/forge-react-boiler.nodejs/webpack/index.js:42:25)
		at clean.then (/home/felipe/forge-react-boiler.nodejs/webpack/index.js:61:3) code: 'MODULE_NOT_FOUND' }
	Cleaning Dir: /home/felipe/forge-react-boiler.nodejs/TMP

**Comment by leefsmp** [comment]
`Starting compiler NODE_ENV=undefined` this means you didn't define `NODE_ENV=development` and `Error: listen EADDRINUSE :::3000` means you have something already running on port 3000.

**Comment by johnfelipe** [comment]
look bro:

	set NODE_ENV=development

	set HOT_RELOADING=true

	sudo nano /home/felipe/forge-react-boiler.nodejs/config/development.config.js

	##
	const PORT = process.env.PORT || 3010
	##

> NODE_ENV=undefined

What i need put in that

And about port i change to 3010, or in other file i need change it?

**Comment by leefsmp** [comment]
I don't know how to help you solve that, you need to check how to use env vars on your platform...

```
NEUC02S806KG8WM:~ leefsmp$ set NODE_ENV=development

NEUC02S806KG8WM:~ leefsmp$ echo $NODE_ENV

development
```

**Comment by johnfelipe** [comment]
In using Ubuntu 14 to 64 bits

**Comment by johnfelipe** [comment]
Done, for ubuntu is:

export NODE_ENV=development

export HOT_RELOADING=true

Is working now, tnks
